/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javabackgaround;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JTextField;
/**
 *
 * @author ASUS
 */
public class frmSettings extends javax.swing.JInternalFrame {
    String urlPath;
    static ImageIcon gambar;
    String values;
    JLabel tempLbl;
    JTextField tempText;
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    frmVoidMain fm = (frmVoidMain)this.getTopLevelAncestor();
    Image image;
    /**
     * Creates new form frmSettings
     */
    public frmSettings(JLabel tempLbl, String sendText) {
//        this.values = value;
        
        this.tempLbl = tempLbl;
//        this.tempText = txtTest;
        initComponents();
        Radio1.setSelected(true);       
        lblValues.setText(values);
//        System.out.println( urlImage());
//        ImageIcon Im = new ImageIcon((getClass().getResource(urlImage())));
//        lblPreview.setIcon(Im);
        }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Radio1 = new javax.swing.JRadioButton();
        Radio2 = new javax.swing.JRadioButton();
        Radio3 = new javax.swing.JRadioButton();
        lblPreview = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblValues = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setTitle("Background Settings");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ButtonGroup.add(Radio1);
        Radio1.setText("Background 1");
        Radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1ActionPerformed(evt);
            }
        });

        ButtonGroup.add(Radio2);
        Radio2.setText("Background 2");
        Radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio2ActionPerformed(evt);
            }
        });

        ButtonGroup.add(Radio3);
        Radio3.setText("Background 3");
        Radio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio3ActionPerformed(evt);
            }
        });

        lblPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Radio3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Radio2)
                        .addComponent(Radio1)))
                .addGap(18, 18, 18)
                .addComponent(lblPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Radio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Radio3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(lblValues, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValues, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//          GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
//          System.out.println(urlImage());
         Dimension defaultToolkit = Toolkit.getDefaultToolkit().getScreenSize();
            gambar = new ImageIcon(getClass().getResource(urlImage()));
            int dX = gambar.getIconWidth();
            int dY = gambar.getIconHeight();
            int xWidth = (defaultToolkit.width-dX)/2;
            int yHeight = (defaultToolkit.height-dY)/2;
            tempLbl.setBounds(xWidth, yHeight, dX, dY);
            tempLbl.setIcon(gambar);
            tempText.setText("Test");
            
            createFileSetting(urlImage());
          dispose();
     
    

    }//GEN-LAST:event_jButton1ActionPerformed
  public String urlImage(){
       String nilai = null;
       Radio1.setActionCommand("1");
       Radio2.setActionCommand("2");
       Radio3.setActionCommand("3");
       String opsi = ButtonGroup.getSelection().getActionCommand();
        switch(opsi){
            case "1":
                nilai = "1.jpg";
                break;
            case "2":
                nilai = "5.jpg";
                break;
            case "3":
                nilai = "2.jpg";
                break;
            default:
                nilai = "pilih salah satu";
                break;
    }

        this.urlPath = nilai;
        return urlPath;
  }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1ActionPerformed
        // TODO add your handling code here:
        callPreview(); 
    }//GEN-LAST:event_Radio1ActionPerformed

    private void Radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio2ActionPerformed
        // TODO add your handling code here:
        callPreview();
    }//GEN-LAST:event_Radio2ActionPerformed

    private void Radio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio3ActionPerformed
        // TODO add your handling code here:
        callPreview();
    }//GEN-LAST:event_Radio3ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
//         String reads = readFilesSetting() ;
//         String urlRead = urlImage();
//        String urlReads;
//        if(readFilesSetting().length() > 0){
////          urlRead = reads;
//        }
        callPreview();
        
    }//GEN-LAST:event_formInternalFrameActivated
    private void createFileSetting(String namaFile){
        try{
            PrintWriter pw = new PrintWriter("Background","UTF-8");
            pw.println(namaFile);
            pw.close();
        }catch(IOException IOE){
            IOE.printStackTrace();
        }
    }
//    private String readFilesSetting(){
//        String namaFile = null;
//        String FILENAME = "Background";
//        try{
//            BufferedReader bf = new BufferedReader(new FileReader(FILENAME));
//            String readFiles = bf.readLine();
//            namaFile = readFiles;
//        }catch(IOException IOE){
//            IOE.printStackTrace();
//        }
//        return namaFile;
//    }
    private void callPreview(){
     this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
       try{
              ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource(urlImage())).getImage().getScaledInstance(lblPreview.getWidth(), lblPreview.getHeight(), Image.SCALE_DEFAULT));
              lblPreview.setIcon(imageIcon);
        }catch(Exception e){
            e.printStackTrace();
        }
       this.setCursor(Cursor.getDefaultCursor());
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JRadioButton Radio1;
    private javax.swing.JRadioButton Radio2;
    private javax.swing.JRadioButton Radio3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JLabel lblValues;
    // End of variables declaration//GEN-END:variables
}
